
Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data. Tensors are also optimized for automatic differentiation.

This code creates a tensor with all 0 values 

In [11]:
import torch

x = torch.empty(2, 4, 3)
print(x)

tensor([[[-6.4767e+09,  1.4195e-42,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])


This code creates a tensor with random values represented as doubles.

In [15]:
import torch

x = torch.rand(2, 4, 3, dtype=torch.double)
print(x)

tensor([[[0.7245, 0.8614, 0.0647],
         [0.4030, 0.6712, 0.8178],
         [0.7883, 0.2454, 0.9307],
         [0.4365, 0.2459, 0.6017]],

        [[0.7573, 0.6390, 0.8580],
         [0.7953, 0.7824, 0.2100],
         [0.8401, 0.7777, 0.0861],
         [0.2394, 0.9469, 0.0705]]], dtype=torch.float64)


This code creates a tensor with values on 1s represented as integers.

In [20]:
import torch

x = torch.ones(2, 4, 3, dtype=torch.int)
print(x)

tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]], dtype=torch.int32)


This code creates a tensor from a python list and print the tensor, its size/shape, its datatype and the device it made on(cpu or gpu).

In [24]:
import torch 
x = torch.tensor([2.5, 0.1])
print(x)
print(f"Shape of tensor: {x.shape}")
print(f"Datatype of tensor: {x.dtype}")
print(f"Device tensor is stored on: {x.device}")

tensor([2.5000, 0.1000])
Shape of tensor: torch.Size([2])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


This code displays how to add two tensors.

In [35]:
import torch 

x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x + y
z2 = torch.add(x, y)
y.add_(x)
print()
print(z)
print()
print(z2)
print()
print(y)

tensor([[0.7464, 0.3832],
        [0.5978, 0.8889]])
tensor([[0.9544, 0.4343],
        [0.2757, 0.5043]])

tensor([[1.7008, 0.8175],
        [0.8735, 1.3932]])

tensor([[1.7008, 0.8175],
        [0.8735, 1.3932]])

tensor([[1.7008, 0.8175],
        [0.8735, 1.3932]])


This code show how to subtract tensors.

In [37]:
import torch 

x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x - y
z2 = torch.sub(x, y)
y.sub_(x)
print()
print(z)
print()
print(z2)
print()
print(y)

tensor([[0.0285, 0.5922],
        [0.8166, 0.1292]])
tensor([[0.4000, 0.4097],
        [0.1232, 0.8954]])

tensor([[-0.3715,  0.1825],
        [ 0.6934, -0.7662]])

tensor([[-0.3715,  0.1825],
        [ 0.6934, -0.7662]])

tensor([[ 0.3715, -0.1825],
        [-0.6934,  0.7662]])


This code shows how to multiply tensors.

In [38]:
import torch 

x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x * y
z2 = torch.mul(x, y)
y.mul_(x)
print()
print(z)
print()
print(z2)
print()
print(y)

tensor([[0.8932, 0.1416],
        [0.6660, 0.8416]])
tensor([[0.3698, 0.4039],
        [0.3571, 0.5528]])

tensor([[0.3303, 0.0572],
        [0.2378, 0.4652]])

tensor([[0.3303, 0.0572],
        [0.2378, 0.4652]])

tensor([[0.3303, 0.0572],
        [0.2378, 0.4652]])


This coe shows how to divide tensors.

In [39]:
import torch 

x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x / y
z2 = torch.div(x, y)
y.div_(x)
print()
print(z)
print()
print(z2)
print()
print(y)

tensor([[0.0350, 0.7984],
        [0.4516, 0.4470]])
tensor([[0.3928, 0.0174],
        [0.1470, 0.4649]])

tensor([[ 0.0890, 45.8682],
        [ 3.0719,  0.9617]])

tensor([[ 0.0890, 45.8682],
        [ 3.0719,  0.9617]])

tensor([[11.2314,  0.0218],
        [ 0.3255,  1.0399]])


How to get slices of a tensor.

In [43]:
import torch 
x = torch.rand(5,3)
print(x)
print()
print(x[:, 0])
print()
print(x[1, :])
print()
print(x[1, 1].item())

tensor([[0.1390, 0.0753, 0.8398],
        [0.6291, 0.7905, 0.2457],
        [0.2179, 0.9418, 0.1725],
        [0.7672, 0.2528, 0.3217],
        [0.0274, 0.1231, 0.5663]])

tensor([0.1390, 0.6291, 0.2179, 0.7672, 0.0274])

tensor([0.6291, 0.7905, 0.2457])

0.7904553413391113


reshaping a tensor

In [49]:
import torch

x = torch.rand(4,4)
print(x)
print(x.size())
y = x.view(16)
print(y)
print(y.size())
print()
y = x.view(-1,8)
print(y)
print(y.size())

tensor([[0.8754, 0.2208, 0.7878, 0.4169],
        [0.3436, 0.3633, 0.9054, 0.7729],
        [0.3998, 0.9058, 0.3081, 0.6685],
        [0.6289, 0.8786, 0.0019, 0.8589]])
torch.Size([4, 4])
tensor([0.8754, 0.2208, 0.7878, 0.4169, 0.3436, 0.3633, 0.9054, 0.7729, 0.3998,
        0.9058, 0.3081, 0.6685, 0.6289, 0.8786, 0.0019, 0.8589])
torch.Size([16])

tensor([[0.8754, 0.2208, 0.7878, 0.4169, 0.3436, 0.3633, 0.9054, 0.7729],
        [0.3998, 0.9058, 0.3081, 0.6685, 0.6289, 0.8786, 0.0019, 0.8589]])
torch.Size([2, 8])


From num_py array to tensor. If the operation is performed on the cpu instead of the gpu the num_py array and tensor will share the same memory location.

In [53]:
import torch
import numpy as np

a = np.ones(5)
print(a)
b= torch.from_numpy(a)
print(b)

a+=1
print(a)
print(b)
print(f"Device tensor is stored on: {b.device}")


[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
Device tensor is stored on: cpu


Show if GPU is available. If so make a tensor on it

In [ ]:
import torch
print(torch.cuda.is_available())
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y.to(device)
    z= x+y
    z = z.to("cpu")


False


: 